# Generated by Django 5.0.7 on 2024-07-20 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_customeraddress_default_addres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customeraddress",
            old_name="default_addres",
            new_name="default_address",
        ),
    ]
