# Generated by Django 5.0.7 on 2024-08-06 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_productrating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductCatagory",
            new_name="ProductCategory",
        ),
    ]
