# Generated by Django 5.0.7 on 2024-08-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="product_imgs/"),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
