# Generated by Django 5.0.7 on 2024-08-07 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_product_image_product_slug_product_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="tag",
            new_name="tags",
        ),
    ]
