# Generated by Django 5.0.7 on 2024-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="demo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
