# Generated by Django 5.0.7 on 2024-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_product_demo_url_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
