# Generated by Django 5.0.7 on 2024-08-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_alter_customer_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitems",
            name="qty",
            field=models.IntegerField(default=1),
        ),
    ]
