# Generated by Django 5.0.7 on 2024-08-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_orderitems_price_orderitems_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.BooleanField(default=False),
        ),
    ]
