# Generated by Django 5.0.7 on 2024-08-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_product_product_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="downloads",
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
