# Generated by Django 5.0.7 on 2024-08-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_vendor_mobile_vendor_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publish_status",
            field=models.BooleanField(default=False),
        ),
    ]
