# Generated by Django 5.0.7 on 2024-09-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_rename_order_status_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="order_status",
            field=models.BooleanField(default=False),
        ),
    ]
