# Generated by Django 5.0.7 on 2024-09-03 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_orderitems_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productrating",
            old_name="reviews",
            new_name="review",
        ),
    ]
