# Generated by Django 5.0.7 on 2024-09-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_rename_reviews_productrating_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(null=True, upload_to="category_imgs/"),
        ),
    ]
